### ISSUE TITLE
[G-2] 사용자는 웹 페이지 헤더를 통해 웹 사이트의 서비스를 확인할 수 있다.

### ISSUE THREAD

**Issue by KIMSEUNGGYU** [CodeSoom/project-react-6-KIMSEUNGGYU#4]
해당 사이트에서 전역적으로 사용하는 Header 기능 구현
- 로고 및 여러 메뉴들로 구성되어 있다.
- 각각의 메뉴는 블로그, 시리즈, 로그인 으로 구성되어 있다.

웹 페이지 헤더의 UI 만 작업.

**Comment by moonkii** [comment]
해당 이슈는 왜 필요한가요?

**Comment by KIMSEUNGGYU** [comment]
> 해당 이슈는 왜 필요한가요?

웹사이트에서 header 영역이 필요하다고 생각해서 issue 로 생성해서 처리했습니다.
header 에서 로고와 메뉴들을 나타내는 기능을 구현하기 위해  생성했습니다.
